//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.07.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef ISCRIPTCALLSTACK_H
#define ISCRIPTCALLSTACK_H


#include "protocol/Protocol.h"
#include "types/DateTime.h"
#include "impl/RdSignal.h"
#include "impl/RdProperty.h"
#include "impl/RdList.h"
#include "impl/RdSet.h"
#include "impl/RdMap.h"
#include "base/ISerializersOwner.h"
#include "base/IUnknownInstance.h"
#include "serialization/ISerializable.h"
#include "serialization/Polymorphic.h"
#include "serialization/NullableSerializer.h"
#include "serialization/ArraySerializer.h"
#include "serialization/InternedSerializer.h"
#include "serialization/SerializationCtx.h"
#include "serialization/Serializers.h"
#include "ext/RdExtBase.h"
#include "task/RdCall.h"
#include "task/RdEndpoint.h"
#include "task/RdSymmetricCall.h"
#include "std/to_string.h"
#include "std/hash.h"
#include "std/allocator.h"
#include "util/enum.h"
#include "util/gen_util.h"

#include <cstring>
#include <cstdint>
#include <vector>
#include <ctime>

#include "thirdparty.hpp"
#include "../instantiations.h"

#include "UE4TypesMarshallers.h"
#include "Runtime/Core/Public/Containers/Array.h"
#include "Runtime/Core/Public/Containers/ContainerAllocationPolicies.h"

#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
/// <summary>
/// <p>Generated from: UE4Library.kt:127</p>
/// </summary>
namespace Jetbrains {
    namespace EditorPlugin {
        
        //abstract
        class IScriptCallStack : public rd::IPolymorphicSerializable
        {
            
            //companion
            
            //custom serializers
            private:
            
            //constants
            public:
            static constexpr rd::wstring_view header{L"Script call stack:", 18};
            
            //fields
            protected:
            
            //initializer
            private:
            void initialize();
            
            //primary ctor
            public:
            
            //secondary constructor
            #ifdef __cpp_structured_bindings
                
                //deconstruct trait
            #endif
            
            //default ctors and dtors
            
            IScriptCallStack();
            
            IScriptCallStack(IScriptCallStack const &) = default;
            
            IScriptCallStack& operator=(IScriptCallStack const &) = default;
            
            IScriptCallStack(IScriptCallStack &&) = default;
            
            IScriptCallStack& operator=(IScriptCallStack &&) = default;
            
            virtual ~IScriptCallStack() = default;
            
            //reader
            static rd::Wrapper<IScriptCallStack> readUnknownInstance(rd::SerializationCtx& ctx, rd::Buffer & buffer, rd::RdId const& unknownId, int32_t size);
            
            //writer
            virtual void write(rd::SerializationCtx& ctx, rd::Buffer& buffer) const override = 0;
            
            //virtual init
            
            //identify
            
            //getters
            
            //intern
            
            //equals trait
            private:
            
            //equality operators
            public:
            friend bool operator==(const IScriptCallStack &lhs, const IScriptCallStack &rhs);
            friend bool operator!=(const IScriptCallStack &lhs, const IScriptCallStack &rhs);
            
            //hash code trait
            virtual size_t hashCode() const noexcept override = 0;
            
            //type name trait
            std::string type_name() const override;
            
            //static type name trait
            static std::string static_type_name();
            
            //polymorphic to string
            private:
            std::string toString() const override;
            
            //external to string
            public:
            friend std::string to_string(const IScriptCallStack & value);
        };
    };
};

#pragma warning( pop )


//hash code trait
namespace rd {
    template <> struct hash<Jetbrains::EditorPlugin::IScriptCallStack> {
        size_t operator()(const Jetbrains::EditorPlugin::IScriptCallStack & value) const noexcept {
            return value.hashCode();
        }
    };
}
#ifdef __cpp_structured_bindings
    
    //tuple trait
#endif


#endif // ISCRIPTCALLSTACK_H
