// Copyright (c) Yevhenii Selivanov

#pragma once

// UE
#include "Components/GameFrameworkComponentManager.h" // EGameFrameworkAddComponentFlags
#include "GameFeatureAction.h"
#include "GameFeatureAction_AddComponents.h" // FGameFeatureComponentEntry
#include "GameFeaturesSubsystem.h" // FGameFeatureStateChangeContext

#include "GfpmAction_AddComponents.generated.h"

/**
 * World-scoped replacement for engine AddComponents action: wraps every per-world iteration in scope guard so synchronously-fired component BeginPlay lands in correct world's pinned context.
 * Avoids context-leak that engine action causes in PIE multiplayer when caller pins global context across all world-context iterations.
 */
UCLASS(DisplayName = "GFPM Add Components")
class GAMEFEATUREPLUGINSMANAGER_API UGfpmAction_AddComponents final : public UGameFeatureAction
{
	GENERATED_BODY()

public:
	/** In engine GFA, default flags are none, causing issues on GFP reactivate. This action improves it, changing defaults, so no need to manually set proper flags. */
	static constexpr uint8 DefaultAdditionFlags = static_cast<uint8>(EGameFrameworkAddComponentFlags::AddUnique | EGameFrameworkAddComponentFlags::UseAutoGeneratedName);

	/** When owning Game Feature Plugin transitions into Active state. */
	virtual void OnGameFeatureActivating(FGameFeatureActivatingContext& Context) override;

	/** When owning Game Feature Plugin transitions out of Active state. */
	virtual void OnGameFeatureDeactivating(FGameFeatureDeactivatingContext& Context) override;

#if WITH_EDITORONLY_DATA
	/** When cooker gathers asset bundle data for owning plugin. */
	virtual void AddAdditionalAssetBundleData(struct FAssetBundleData& AssetBundleData) override;
#endif // WITH_EDITORONLY_DATA
#if WITH_EDITOR
	/** When editor validates Game Feature Data asset that owns this action. */
	virtual EDataValidationResult IsDataValid(class FDataValidationContext& Context) const override;

	/** When ComponentList entry is added in editor. */
	virtual void PostEditChangeProperty(struct FPropertyChangedEvent& PropertyChangedEvent) override;

	/** Adds new entry to component list.
	 * @param ActorClass Actor class that receives component.
	 * @param ComponentClass Component class added to that actor.
	 * @param bClientComponent If true, entry applies on client.
	 * @param bServerComponent If true, entry applies on server. */
	UFUNCTION(BlueprintCallable, Category = "[Game Feature Plugins Manager]")
	void AddComponentEntry(TSubclassOf<AActor> ActorClass, TSubclassOf<UActorComponent> ComponentClass, bool bClientComponent = true, bool bServerComponent = true);
#endif // WITH_EDITOR

	/** Repeats the same entries from engine GFA. */
	UPROPERTY(EditAnywhere, Category = "[Game Feature Plugins Manager]", meta = (TitleProperty = "{ActorClass} -> {ComponentClass}"))
	TArray<FGameFeatureComponentEntry> ComponentList;

private:
	struct FGfpmContextHandles
	{
		FDelegateHandle GameInstanceStartHandle;
		/** Component request handles bucketed by FWorldContext::ContextHandle so deactivation can scope-guard per-world handle release. */
		TMap<FName, TArray<TSharedPtr<struct FComponentRequestHandle>>> ComponentRequestHandlesByWorld;
	};

	/** Per-world component request enqueue against world's framework component manager. */
	void AddToWorld(const struct FWorldContext& WorldContext, FGfpmContextHandles& Handles);

	/** When GameInstance starts after this action's activation. */
	void HandleGameInstanceStart(class UGameInstance* GameInstance, FGameFeatureStateChangeContext ChangeContext);

	TMap<FGameFeatureStateChangeContext, FGfpmContextHandles> ContextHandles;
};
