[/Script/NetworkPrediction.NetworkPredictionSettingsObject]
; Mover - tweaked next for smooth movement:
; - SimulatedProxyNetworkLOD = Interpolated
; - bEnableFixedTickSmoothing = true
Settings=(PreferredTickingPolicy=Fixed,ReplicatedManagerClassOverride=None,FixedTickFrameRate=60,bForceEngineFixTickForcePhysics=True,SimulatedProxyNetworkLOD=Interpolated,bEnableFixedTickSmoothing=True,FixedTickInterpolationBufferedMS=100,IndependentTickInterpolationBufferedMS=100,IndependentTickInterpolationMaxBufferedMS=250,FixedTickInputSendCount=30,IndependentTickInputSendCount=30,MaximumRemoteInputFaultLimit=6)
