[/Script/Bomber.BmrGameUserSettings]
OverallQuality=2
FPSLockIndex=0
; 1 - WindowedFullscreen (Native Fullcreen is not supported)
FullscreenMode=1
FrameRateLimit=0
AppliedCulture=
bIsFPSCounterEnabled=False

[/Script/Bomber.BmrCameraComponent]
bIsCameraLockedOnCenter=True

[/Script/Bomber.BmrPlayerState]
PlayerNameCustom=

[/Script/Bomber.BmrSoundsSubsystem]
MasterVolume=1.0
MusicVolume=1.0
SFXVolume=1.0

[/Script/Bomber.BmrGameDifficultySubsystem]
DifficultyTag=(TagName="Difficulty.Easy")
