[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=6A39FFB248B3B4A0D4B1449C281E8DF2
ProjectName=Bomberrage
CompanyName=Yevhenii Selivanov
Homepage=github.com/JanSeliv/Bomber
ProjectDisplayedTitle=NSLOCTEXT("[/Script/EngineSettings]", "A6FA60EA4BD76CE382E8BB940382F110", "Bomberrage")
CopyrightNotice=Copyright (c) Yevhenii Selivanov
ProjectDebugTitleInfo=NSLOCTEXT("[/Script/EngineSettings]", "2FF6B8A142E2A7F366C0F88EA33B7DAA", "Bomberrage")
Description=Open-source Bomberman game made in UE5
MinWindowWidth=1280
MinWindowHeight=720
bAllowWindowResize=False
bAllowMaximize=False

[Staging]
+AllowedConfigFiles=Bomber/Config/DefaultDataAssets.ini
+AllowedConfigFiles=Bomber/Config/DefaultMetaCheatManager.ini
+AllowedConfigFiles=Bomber/Config/DefaultModelViewViewModel.ini
+AllowedConfigFiles=Bomber/Config/DefaultModularGameFeatures.ini
+AllowedConfigFiles=Bomber/Config/DefaultNetworkPrediction.ini
+AllowedConfigFiles=Bomber/Config/DefaultPoolManager.ini
+AllowedConfigFiles=Bomber/Config/DefaultSettingsWidgetConstructor.ini
+AllowedConfigFiles=Bomber/Config/Tags/DefaultAbilitiesTags.ini
+AllowedConfigFiles=Bomber/Config/Tags/DefaultPlayerTags.ini
+AllowedConfigFiles=Bomber/Config/Tags/DefaultSettingsTags.ini
+AllowedConfigFiles=Bomber/Config/Tags/DefaultDifficultyTags.ini
+AllowedConfigFiles=Bomber/Config/Tags/DefaultUITags.ini

[/Script/Engine.AssetManagerSettings]
-PrimaryAssetTypesToScan=(PrimaryAssetType="Map",AssetBaseClass=/Script/Engine.World,bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game/Maps")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
-PrimaryAssetTypesToScan=(PrimaryAssetType="PrimaryAssetLabel",AssetBaseClass=/Script/Engine.PrimaryAssetLabel,bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
+PrimaryAssetTypesToScan=(PrimaryAssetType="Map",AssetBaseClass="/Script/Engine.World",bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game/Maps")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
+PrimaryAssetTypesToScan=(PrimaryAssetType="PrimaryAssetLabel",AssetBaseClass="/Script/Engine.PrimaryAssetLabel",bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
+PrimaryAssetTypesToScan=(PrimaryAssetType="GameFeatureData",AssetBaseClass="/Script/GameFeatures.GameFeatureData",bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=((Path="/Game/Unused")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=AlwaysCook))
; Include primary data assets, so Data Assets Loader plugin can find them and load on demand
+PrimaryAssetTypesToScan=(PrimaryAssetType="DalPrimaryDataAsset",AssetBaseClass="/Script/DataAssetsLoader.DalPrimaryDataAsset",bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=((Path="/Game/Bomber/DataAssets")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=AlwaysCook))
bOnlyCookProductionAssets=False
bShouldManagerDetermineTypeAndName=False
bShouldGuessTypeAndNameInEditor=True
bShouldAcquireMissingChunksOnLoad=False
bShouldWarnAboutInvalidAssets=True
MetaDataTagsForAssetRegistry=()

[/Script/DataRegistry.DataRegistrySettings]
+DirectoriesToScan=(Path="/Game/Bomber/DataRegistries")

[/Script/UnrealEd.ProjectPackagingSettings]
bCompressed=True
FullRebuild=True
Build=Always
; begin Build size optimization
BuildConfiguration=PPBC_Shipping
IncludeCrashReporter=False
IncludeDebugFiles=False
IncludePrerequisites=False
PackageCompressionLevel_DebugDevelopment=9
PackageCompressionLevel_TestShipping=9
PackageCompressionLevel_Distribution=9
; end Build size optimization
; Include the Slate folder with mouse cursor
+DirectoriesToAlwaysStageAsNonUFS=(Path="Slate")
; Include the Gameplay Cue assets
+DirectoriesToAlwaysCook=(Path="/Game/Bomber/AbilitySystem/GameplayCues")
; Localization support
+CulturesToStage=en
+CulturesToStage=nl
+CulturesToStage=fr
+CulturesToStage=it
+CulturesToStage=ar
+CulturesToStage=tr
+CulturesToStage=uk
+CulturesToStage=vi
+CulturesToStage=zh-Hant
+CulturesToStage=es-419
+CulturesToStage=pt-PT
+CulturesToStage=ro
+CulturesToStage=ru
+CulturesToStage=sv
+CulturesToStage=th
+CulturesToStage=zh-Hans
+CulturesToStage=el
+CulturesToStage=hu
+CulturesToStage=id
+CulturesToStage=ja
+CulturesToStage=ko
+CulturesToStage=no
+CulturesToStage=pl
+CulturesToStage=pt-BR
+CulturesToStage=bg
+CulturesToStage=cs
+CulturesToStage=da
+CulturesToStage=de
+CulturesToStage=es
+CulturesToStage=fi
; Enable `All` languages from above in the build
InternationalizationPreset=All

[Internationalization]
+LocalizationPaths=%GAMEDIR%Content/Localization/InGameSettings

[/Script/GameplayAbilities.AbilitySystemGlobals]
+GlobalAttributeSetDefaultsTableNames=/Game/Bomber/AbilitySystem/Attributes/CT_Attributes_Powerups_Max.CT_Attributes_Powerups_Max
+GlobalAttributeSetDefaultsTableNames=/Game/Bomber/AbilitySystem/Attributes/CT_Attributes_Powerups_Base.CT_Attributes_Powerups_Base
+GlobalAttributeSetDefaultsTableNames=/Game/Bomber/AbilitySystem/Attributes/CT_Attributes_Health.CT_Attributes_Health
+GameplayCueNotifyPaths=/Game/Bomber/AbilitySystem/GameplayCues

[/Script/AsyncMessageSystem.AsyncMessageDeveloperSettings]
; Listen events in editor-not-PIE-world (e.g: GeneratedMap_Ready)
bEnableWorldSubsystemInEditor=True
